server:
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
    #    cache: true
    cache: false

  redis:
    host: 172.18.0.22
